modulefiles/modulefile.ProdGSI.hera
From Leslie Hart
The current method of loading "sutils" module:
module load contrib
module load sutils
The new method for loading “sutils” module (available now, and required starting 6/11/20):
module use -a /contrib/sutils/modulefiles
module load sutils
GSI modulefile for Hera has been modified to support these changes
=> Hotfix to allow for contrib modules to still load on Hera

src/enkf/mpi_readobs.f90
in src/enkf/mpi_readobs, if the ensemble spread in observation space exceeds a value of 1000 a print statement is triggered that tries to print an array (mem_ob) that has already been deallocated.  This causes a segfault on Orion.  The fix is simply to not print mem_ob.  
Does not affect results, but protects against a possible segfault if ensemble spread exceeds the threshold value.
=> fix a bug in EnKF that can cause segfault in a diagnostic print 

ush/calcanl_gfs.py
There is a typo in ush/calcanl_gfs.py that causes the gdasanalcalc job to fail when IAU is off. This fixes it.
=> Bugfix for incorrect function call when IAU is off

ush/calcanl_gfs.py
Add print statements if increment or ensemble guess files are missing but $IAUFHRS says it should be there.
This has not been tested but *shouldn't* do anything besides add extra print statements.
This will hopefully help users notice errors in previous steps.
=> Add in some useful print statements

scripts/exglobal_enkf_chgres_fv3gfs.sh.ecf
Don't merge in until corresponding changes have been merged into global-workflow/feature/gfsv16b.
Changes one line of namelist generation from vcoord_file=$SIGLEVEL to ref_file to be the same as terrain_file.
=> Change gdasechgres namelist for new version of enkf_chgres_recenter_ncio

src/gsi/read_obs.F90, src/gsi/read_satwnd.f90
AMV_Genkova_parallel_ncio_LG - branch adding LeoGeo AMVs to GSI
Please see the GitHub Issue [#24](https://github.com/NOAA-EMC/GSI/issues/24) for more details.
=> GitHub Issue NOAA-EMC/GSI#24. Add LeoGeo AMVs in GSI.

modulefiles/modulefile.ProdGSI.wcoss, modulefiles/modulefile.ProdGSI.wcoss_c, modulefiles/modulefile.ProdGSI.wcoss_d
The old bufr versions won't work after 2020 Dec 31, so all of the
module versions are updated to the most recent versions on WCOSS.
Refs: #77
=> Update bufr modules on WCOSS

src/gsi/read_l2bufr_mod.f90
fix the issue of GSI failure due to checking subset status before reading data. This checking step is not necessary and should be turned off.
=> GitHub Issue NOAA-EMC/GSI#81. Fix the issue of reading NEXRAD bufr file.

util/Conventional_Monitor/image_gen/ush/Transfer.sh, util/Conventional_Monitor/image_gen/ush/transfer_imgs.sh
The ConMon file transfer scripts were overhauled and renamed using Transfer.sh and transfer.sh.  This created a potential file collision for MacOS and any other file systems that are case insensitive.  Renaming transfer.sh to transfer_imgs.sh fixes the problem.
=> Fix issue #104, remove file collision in ConMon

src/gsi/get_gefs_for_regional.f90, src/gsi/gridmod.F90, src/gsi/gsi_rfv3io_mod.f90, src/gsi/gsimod.F90, src/gsi/mod_fv3_lola.f90
For this PR:
1) The current GSI can not handle the FV3LAM grid orientation W-E/S-N (SW corner is the first grid point).
The new code was added based on the current GSI FV3LAM interface to handle both grid orientation:
_E-W N-S grid
W-E S-N grid_
2) Bug fix (terrain interpolation) in regional GSI hybrid with dual-resolution ensemble forecast
=> Enhance  GSI to work with two FV3LAM grid orientations.

src/gsi/crtm_interface.f90
In line 933 in setuprad.f90, the function call_crtm is called without the optional parameter 'stability'. The function call_crtm has been assigning a value to stability without checking if it is present. This fixes this bug.
=> call_crtm bug fix for gmi

jobs/JGDAS_ATMOS_ANALYSIS_DIAG, jobs/JGDAS_ENKF_DIAG, util/Radiance_Monitor/data_extract/ush/radmon_err_rpt.sh
Final changes for GFS v16 that have not been merged to the NOAA-EMC/GSI authoritative master.
=> GitHub Issue NOAA-EMC/GSI#2.  Final changes for GFSv16.

modulefiles/modulefile.ProdGSI.wcoss_c, src/gsi/get_gefs_for_regional.f90
Update of modulefile.ProdGSI.wcoss_c and get_gefs_for_regional.f90 bug fixes.
=> GitHub Issue NOAA-EMC/GSI#152. 

src/gsi/setupcldtot.F90, src/gsi/setuplwcp.f90, src/gsi/setupq.f90, src/gsi/setupswcp.f90
As documented in NOAA-EMC/GSI issue #174, four setup routines in `src/gsi` are missing the optional argument `append_diag` in the call to `nc_diag_init`.   For those cases in which the GSI reads data for a given observation type from multiple input files variable `append_diag` is set to `.true.` so that the file pointer is correctly on subsequent calls to the given setup routine.   Without `append_diag` present, the resulting netcdf diagnostic files do not properly capture all information for the given observation type.   
This bug is present in the following `src/gsi` files:  `setupcldtot.F90`, `setuplwcp.f90`, `setupq.f90`, `setupswcp.f90`.
This bug impacts conventional data monitoring of q observations.   This bug also impacts the assimilation of q observations by the EnKF update code.
=> GitHub Issue NOAA-EMC/GSI#174 correct append_diag bug

scripts/exgdas_enkf_select_obs.sh
Issue #180 documents a bug found during TAC2BFR parallel testing.  Script `exgdas_enkf_select_obs.sh` contains a typo.   The filename `obs_input.tar` should be `obsinput.tar`.   The bug generates a `No such file` error message when the script is executed.  The bug does not alter analysis results.   
This PR is opened to merge the bug fix (correct the typo) into the authoritative master.
=> GitHub Issue NOAA-EMC/GSI#180.  correct typo in exgdas_enkf_select_obs.sh

src/gsi/setupbend.f90
Change commercial ro obs errors/qc and add Lidia's fixes
Github issue #200
=> updates to setupbend

src/gsi/balmod.f90, src/gsi/glbsoi.f90, src/gsi/gsi_rfv3io_mod.f90, src/gsi/gsimod.F90, src/gsi/m_berror_stats.f90, src/gsi/m_berror_stats_reg.f90, src/gsi/prewgt_reg.f90
…nal FV3 DA (FV3LAMDA)
This change allows the use of the global berror stats file in the regional runs.  Compared to the regional berror file, the global berror file is missing the second record that contains the latitudes and sigma's of the statistics.  Also, the dimensions of the arrays are different with the regional berror file containing some arrays that start with latitude 0 and end with latitude nlats+1.
To accommodate  the differences, a new global stats file was created which includes the second record containing the lats and sigmas.  This file is in /scratch1/NCEPDEV/da/John.Derber/git/gsi/berror_stats on Hera.  The global run will detect automatically whether the new or old format file is used and will run properly for either file.   For the regional, the default values will …
=>  GitHub Issue NOAA-EMC/GSI#175. Use the global 127L B-Matrix in regional FV3 DA (FV3LAMDA)

src/gsi/read_nsstbufr.f90
This fix is documented in Issue #208 by Xu Li.
It is to be incorporated into the GFS v16.1.3 upgrade (Issue #200).
=> Modify read_nsstbufr for new ships data 

src/gsi/correlated_obsmod.F90
This update will allow for easier handling of correlated error in the case that an instrument has failures in active channels. If CrIS N20 looses the midwave channels, the only necessary change will be to the satinfo file. There is also the option now to turn on channels in the satinfo, without affecting correlated error.
If no changes are made to the satinfo, this update will not result in any difference to GSI results.
=> GitHub Issue NOAA-EMC/GSI#212 updates to correlated error code

scripts/exgdas_enkf_update.sh, scripts/exglobal_atmos_analysis.sh, scripts/exglobal_diag.sh, src/enkf/innovstats.f90, src/gsi/correlated_obsmod.F90, src/gsi/gsimod.F90, src/gsi/obsmod.F90, src/gsi/read_nsstbufr.f90, src/gsi/read_ozone.f90, src/gsi/setupoz.f90, util/Correlated_Obs/cov_calc.f90, util/Correlated_Obs/readsatobs.f90
Issue #237 documents the merge of the authoritative `master` at 2f28fbf into a forked copy of the authoritative `release/gfsda.v16.x` at 3898ab4.   The merge was done in @RussTreadon-NOAA 's forked `release/gfsda.v16.x` and completed at a723db1.   From here, the forked `release/gfsda.v16.x` was squash merged into the forked `master`.   Done at d4645c1
This PR is opened to merge the forked `master` into the authoritative `master`.
=> GitHub Issue NOAA-EMC/GSI#237: merge release/gfsda.v16.x at a723db1 into master

modulefiles/modulefile.ProdGSI.wcoss2, ush/build_all_cmake.sh
1) Port GSI for GEFSv12 to WCOSS2
2) Update build modules to remove hardwired version numbers
On branch feature/gefs_v12_port2wcoss2
Changes to be committed:
new file:   modulefiles/modulefile.ProdGSI.wcoss2
modified:   ush/build_all_cmake.sh
Refs: #183
=> Port gsi to WCOSS2 & Remove hardwired version nums

src/gsi/berror.f90, src/gsi/compute_derived.f90, src/gsi/compute_qvar3d.f90, src/gsi/constants.f90, src/gsi/crtm_interface.f90, src/gsi/evalqlim.f90, src/gsi/genqsat.f90, src/gsi/gsimod.F90, src/gsi/intjcmod.f90, src/gsi/jfunc.f90, src/gsi/observer.F90, src/gsi/pcgsoi.f90, src/gsi/prt_guess.f90, src/gsi/read_guess.F90, src/gsi/setupcldtot.F90, src/gsi/setupq.f90, src/gsi/setuprhsall.f90, src/gsi/setupw.f90, src/gsi/stpcalc.f90, src/gsi/stpjcmod.f90, src/gsi/stpw.f90, src/gsi/update_guess.f90
This change fixes bug in the vqc for winds.  Also, in modifies the minimization algorithm so that it can detect nonlinearities.  The minimization algorithm should produce the same results within round-off.  Two new options are included.  1. To allow supersaturation (superfact).  2. To limit qobs to a value equal to superfact*qsat.  The second option was included because there was a case found where there were many hurricane recon obs that produced q values greater than the supersaturated value with the analysis.  This resulted in slow convergence.  Both of these factors are set to values that will not impact the results (superfact=1.0, limitqobs = .false.  
The resulting changes make resets very unlikely when the vqc option is used.  Also, the nonlinearity diagnostic is very useful when …
=> GitHub Issue NOAA-EMC/GSI#219. Improve minimization and fix bug in vqc

util/Ozone_Monitor/nwprod/gdas_oznmon/fix/gdas_oznmon_satype.txt
Update gdas_oznmon_satype.txt file to remove reference to gome_metop-a.
=> GSI GitHub Issue NOAA-EMC/GSI#253.  Update OznMon satype file.

util/Radiance_Monitor/nwprod/radmon_shared.v3.0.0/ush/radmon_verf_time.sh
Changed cp to mv for RadMon's warning files (bad_*.txt).  The common workflow uses the same directory for RadMon and OznMon processing and the RadMon's bad_pen.${PDY} file was ending up in both the RadMon and OznMon $TANKdir locations.  Changing the RadMon's copy to a move fixes that.
=> Change cp to mv for RadMon's warning files.

jobs/JGDAS_ATMOS_ANALYSIS_DIAG, jobs/JGDAS_ATMOS_CHGRES_FORENKF, jobs/JGDAS_ENKF_DIAG, jobs/JGDAS_ENKF_ECEN, jobs/JGDAS_ENKF_FCST, jobs/JGDAS_ENKF_POST, jobs/JGDAS_ENKF_SELECT_OBS, jobs/JGDAS_ENKF_SFC, jobs/JGDAS_ENKF_UPDATE, jobs/JGLOBAL_ATMOS_ANALYSIS, jobs/JGLOBAL_ATMOS_ANALYSIS_CALC
This PR:
- removes references for `jlogfile` and `postmsg` from the Global GSI J-Jobs.
=> Remove jlogfiles and postmsg from JJOBS.

scripts/exgdas_efsoi_update.sh, scripts/exgdas_enkf_update.sh, scripts/exglobal_atmos_analysis.sh, src/gsi/gsi_obOperTypeManager.F90, src/gsi/ncepnems_io.f90, src/gsi/qcmod.f90, src/gsi/radiance_mod.f90, src/gsi/radinfo.f90, src/gsi/read_obs.F90, src/gsi/read_viirs.f90, src/gsi/satthin.F90, src/gsi/setuprad.f90
This PR is to incorporate an NSST package into GSI master.
This package includes 4 items:
The update of the horizontal background error correlation length (hsst)
The reduction of the thinning mesh from 145 km to 70 km for AVHRR and VIIRS radiances. The capability to apply multiple and hsst dependent thinning mesh for AVHRR and VIIRS is included in the code changes and it is optional and controlled by dmesh (applied when it is 888.0). This option is tested with GFSv15.2 C768 but not in GFSv16.0 C384 experiment. 
The exclusion of the partly clear AVHRR radiance
The addition of VIIRS radiance, including NPP and J1/N20
This package has been tested with GFSv15.2 at full resolution (C768), the whole package and individual item. The results have shown a significant improved GFS NSST analysis. It …
=> GitHub Issue NOAA-EMC/GSI#235. An NSST update package for GFSv16.5

src/gsi/general_read_gfsatm.f90, src/gsi/read_obs.F90
Applied bug fix to general_read_gfsatm.f90 to correct the MPI rank issue where L127runs hang with 1020 or more tasks.  Also, added ",silent=.true." to the call to unformatted_open in read_obs.F90 to remove warning messages in the output.
Changes were run on Dogwood and results are reproducible.
=> GitHub Issue NOAA-EMC/GSI#246.  Applied bug fix to general_read_gfsatm.f90 and read_obs.F90

src/gsi/gsi_rfv3io_mod.f90
A quick fix for the corrupted final statistics in files like fort.201. See GSI ISSUE https://github.com/NOAA-EMC/GSI/issues/272.
=> GitHub Issue NOAA-EMC/GSI#272. A fix for the corrupted final statistics written out in the GSI FV3-LAM parallel IO for cold start runs

scripts/exgdas_enkf_sfc.sh, scripts/exglobal_atmos_analysis.sh
The GSI scripts, exglobal_atmos_analysis.sh and exgdas_enkf_sfc.sh, are modified to make the GSI generated NSST foundation temperature file. as an input to global_cycle, have the same name in ufs_utils. See GSI Issue: https://github.com/NOAA-EMC/GSI/issues/303.
This change is limited to these two GSI scripts only, no code change. It is in the frame of workflow, no need to run regression test. 
It is treated as a hotfix. 
The change has been done in feature/gsinsst_scripts_only branch. It is ready to be committed to master.
=> GitHub Issue NOAA-EMC/GSI#303. Modifications of two GSI scripts to the filename being consistent with the change in ufs_utils

src/gsi/read_obs.F90, src/gsi/read_prepbufr.f90, src/gsi/read_satwnd.f90, src/gsi/setupw.f90
This branch brings:
- code to write out AMVQ mitigation flag into NetCDF diag file
- code to read Metop-B/C AMVs and Him-8 AMVs from new BUFR
- station_id bug fix for polar winds
=> GitHub Issue NOAA-EMC/GSI#243.  AMVs changes to v16x
