src/read_obs.F90, src/read_satwnd.f90
Bring EUM bufr code changes into a new GSI version (v15.3.3) for operational implementation
=> Bring EUM bufr code changes to OPS :: release/gfsda.v15.3.3

src/gsi/aniso_ens_util.f90, src/gsi/get_gefs_for_regional.f90, src/gsi/gfs_stratosphere.f90, src/gsi/gsi_rfv3io_mod.f90, src/gsi/read_fl_hdob.f90, src/gsi/read_prepbufr.f90, src/gsi/read_radar.f90, src/gsi/read_radar_wind_ascii.f90, src/gsi/read_rapidscat.f90, src/gsi/read_satwnd.f90, src/gsi/read_sfcwnd.f90, src/gsi/setupuwnd10m.f90, src/gsi/setupvwnd10m.f90, src/gsi/setupw.f90
This is to push back recent fixes/developments for GSI interface for FV3SAR. Thanks to collaborators Ming Hu , Hongli Wang at GSL for pointing out the problem and reporting suspicious behavior of the codes. 
For more details see the ticket : pushing back the recent developments fixes with FV3SAR GSI interface in the branch gsi_fv3reg4coldstart #26
=> GitHub Issue NOAA-EMC/GSI#26.  Pushing back the recent developments fixes with FV3SAR GSI interface in the branch gsi_fv3reg4coldstart.

src/gsi/read_seviri.f90
Currently, the CSR is read correctly, but not for ASR data. This PR is to fix a bug in read_seviri.f90 for ASR data. This change does not affect GSI analysis results if reading in CSR data. My tests have shown identical results with SEVIRI CSR data.
=> bug fix for reading seviri asr data

modulefiles/modulefile.ProdGSI.jet, src/gsi/gsimod.F90, src/gsi/gsisub.F90, src/gsi/obsmod.F90, src/gsi/read_l2bufr_mod.f90, src/gsi/read_obs.F90, src/gsi/read_radar.f90, src/gsi/setuprw.f90
TDR and 88D thinning code changes for HWRF GSI
=> GitHub Issue NOAA-EMC/GSI#46.  TDR update for HWRF.

src/gsi/setupt.f90
GitHub Issue NOAA-EMC/GSI#85 bug fix for checking ges_z allocation status in setupt.f90
=> GitHub Issue NOAA-EMC/GSI#85 bug fix 

src/gsi/general_read_gfsatm.f90
PR to update GSI global parallel netcdf read to use communicator.   Details provided in issue #91.
=> Issue #91:  use communicator in global parallel netcdf read

src/gsi/setupt.f90
deallocate ges_th2 and ges_q2 in setupt.f90
=> GitHub Issue NOAA-EMC/GSI#94 deallocate ges_q2 and ges_th2 in setupt.f90

src/enkf/gridio_fv3reg.f90, src/enkf/observer_fv3reg.f90
Update enkf for fv3sar following interface changes ,like, in readgridata, in the enkf for gfs.  
This update only incorporates changes in the interface like including dummy subroutine readgridata_pnc  while without actual implementation of those new functions.  They are to be finished in the future.
=> GitHub Issue NOAA-EMC/GSI#89. Update enkf4fv3sar following the EMC GSI master.

scripts/exglobal_atmos_analysis.sh, src/gsi/gsimod.F90, src/gsi/guess_grids.F90, src/gsi/setupbend.f90
This PR adds namelist options associated with the assimilation of commercial RO. An update to the fix directory will be necessary to actually turn on the commercial data. See [issue #128](https://github.com/NOAA-EMC/GSI/issues/128)
=> Commercial RO changes for Release/gfsda.v16.1.0

util/Ozone_Monitor/nwprod/oznmon_shared/sorc/oznmon_horiz.fd/oznmon_read_diag.f90, util/Ozone_Monitor/nwprod/oznmon_shared/sorc/oznmon_time.fd/oznmon_read_diag.f90, util/Ozone_Monitor/nwprod/oznmon_shared/sorc/oznmon_time.fd/time.f90
Issues with reading NetCDF formatted diag files resulted in inconsistent results on successive runs using the same data.  
@RussTreadon-NOAA  I don't have permission to assign reviewers but you might want to take a look.
=> GitHub Issue NOAA-EMC/GSI#150.  Correct OznMon read diag issue.

jobs/JGDAS_EFSOI, jobs/JGDAS_EFSOI_ECEN, jobs/JGDAS_EFSOI_FCST, jobs/JGDAS_EFSOI_POST, jobs/JGDAS_EFSOI_SFC, jobs/JGDAS_EFSOI_UPDATE
Changes to jobs directory:
new file:   jobs/JGDAS_EFSOI
new file:   jobs/JGDAS_EFSOI_ECEN
new file:   jobs/JGDAS_EFSOI_FCST
new file:   jobs/JGDAS_EFSOI_POST
new file:   jobs/JGDAS_EFSOI_SFC
new file:   jobs/JGDAS_EFSOI_UPDATE
Each of these files is needed to set up the environment for EFSOI-specific tasks; some call existing scripts, others need scripts specific to EFSOI
=> EFSOI additions to jobs directory for issue #118

src/gsi/cplr_get_fv3_regional_ensperts.f90, src/gsi/mod_fv3_lola.f90, src/gsi/write_fv3_spread.f90
it is associated with https://github.com/NOAA-EMC/GSI/issues/189.
Now, the GSI can dump ensemble spread on the ensemble analysis grid for FV3-LAM ensembles.
=>  GitHub Issue NOAA-EMC/GSI#189. Add working write_fv3_spread for fv3-lam

src/gsi/read_l2bufr_mod.f90
GSI bug fix to resolve this issue which caused HWRF self-cycled DA failure.
=> GitHub Issue NOAA-EMC/GSI#206. Bug fix which cause HWRF self-cycled DA system failure.

util/Conventional_Monitor/data_extract/ush/MkBase.pl
Updated MkBase utility adding the option of updating the historic obs counts of only a single data type (i.e. t120) instead of all data types.
=> GSI issue #220.  Update MkBase utility.  Completes #220.

src/gsi/read_nsstbufr.f90, src/gsi/setupbend.f90
This PR pulls the changes from v16.1.4 (#200) into the v16.x release branch.  It is the same as PR #222 but for release/gfsda.v16.x rather than the master.
=> GSI Issue #200: Incorporating GFS v16.1.4 (DO-3 and NSST)

util/Conventional_Monitor/ConMon_install.pl, util/Conventional_Monitor/build_ConMon_cmake.sh, util/Conventional_Monitor/data_extract/ush/ConMon_DE.sh, util/Conventional_Monitor/get_hostname.pl, util/Conventional_Monitor/image_gen/ush/mk_horz_hist.sh, util/Conventional_Monitor/image_gen/ush/mk_time_vert.sh, util/Conventional_Monitor/image_gen/ush/plot_horz.sh, util/Conventional_Monitor/image_gen/ush/plot_horz_uv.sh, util/Conventional_Monitor/nwprod/gdas_conmon/driver/test_jgdas_vcmon_wcoss2.sh, util/Conventional_Monitor/parm/ConMon_config
Initial port of ConMon to wcoss2.  No part of the ConMon is currently in operations so the GSI/master fork has been used for this port.  Also note that while testing has been completed successfully on wcoss2, the minimal data set available hardly provides a real world stress test, so adjustments may well have to be made once operational data (or expanded testing data) becomes available.
=> GSI GitHub Issue NOAA-EMC/GSI#228.  Port ConMon to wcoss2.

src/enkf/enkf.f90, src/enkf/enkf_obs_sensitivity.f90, src/enkf/enkf_obsmod.f90
Changes to the following files:
src/enkf/enkf_obsmod.f90
src/enkf/enkf_obs_sensitivity.f90
src/enkf/enkf.f90
In serial filter, creates array size of number of observations and sets whether they are assimilated or not, and then sends to osense file if ran in efsoi mode.
=> GitHub Issue NOAA-EMC/GSI#259. Add assimilated flag to observations in osense file

src/gsi/read_nsstbufr.f90
A GSI code change to assimilate three types of in situ sea water temperature observation is ready to merge. See https://github.com/NOAA-EMC/GSI/issues/270
=> GitHub Issue NOAA-EMC/GSI#270. GSI code change to assimilate Saildrone, Argo and Glider in GFS NSST

jobs/JGDAS_EFSOI, jobs/JGDAS_EFSOI_FCST, scripts/exgdas_efsoi.sh, scripts/exgdas_efsoi_update.sh
These are catching up various EFSOI-specific scripts: changes to reflect GSI and global-workflow, some refactoring
Files included:
jobs/JGDAS_EFSOI
jobs/JGDAS_EFSOI_FCST
scripts/exgdas_efsoi.sh
scripts/exgdas_efsoi_update.sh
=> GitHub Issue NOAA-EMC/GSI#311. Update scripts needed for EFSOI 

util/EFSOI_Utilities/src/efsoi.f90, util/EFSOI_Utilities/src/loadbal_efsoi.f90
Update of master to EFOSI development branch for code factoring of code in util/EFSOI_Utilities/src 
Files changed:
loadbal_efsoi.f90
efsoi.f90
These entail only the changing of variable names, nothing to affect the functionality. The code has been used as is for a number of months and should be good as is.
=> GitHub Issue NOAA-EMC/GSI#316 Refactoring of EFSOI code

src/gsi/hdraobmod.f90
…th GNU compiler found by Rahul.
=> GitHub Issue NOAA-EMC/GSI#314. Modify hdraobmod.f90 to fix problem with GNU compiler found by Rahul.
